version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d:ro
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql-data:/var/lib/mysql

    env_file:
      - ./mysql/local.env
    tty: true
  api:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./app
      dockerfile: debugger.Dockerfile
    restart: unless-stopped
    environment:
      - DEBUG=true
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./app/local.env